In [3]:
#数组的运算
import numpy as np
import pandas as pd
array35=np.arange(1,10)
print(array35)
print(array35+10)
print(array35*10)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
[10 20 30 40 50 60 70 80 90]


In [2]:
array36 = np.array([1, 1, 1, 2, 2, 2, 3, 3, 3])
print(array35 + array36)
print(array35 * array36)
print(array35 ** array36)

[ 2  3  4  6  7  8 10 11 12]
[ 1  2  3  8 10 12 21 24 27]
[  1   2   3  16  25  36 343 512 729]


In [4]:
print(np.sqrt(array35))
print(np.log2(array35))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [5]:
array37 = np.array([[4, 5, 6], [7, 8, 9]])
array38 = np.array([[1, 2, 3], [3, 2, 1]])
print(array37 ** array38)
print(np.power(array37, array38))

[[  4  25 216]
 [343  64   9]]
[[  4  25 216]
 [343  64   9]]


In [ ]:
#floor_divide(x, y) / mod(x, y) 整除函数 / 求模函数
#multiply(x, y) / divide(x, y) 乘法函数 / 除法函数
#add(x, y) / substract(x, y) 加法函数 / 减法函数
#maximum(x, y) / fmax(x, y)  两两比较元素获取最大值 / 获取最大值（忽略NaN）
#minimum(x, y) / fmin(x, y)  两两比较元素获取最小值 / 获取最小值（忽略NaN）
#dot(x, y) 点积运算（数量积，通常记为$\cdots$，用于欧几里得空间（Euclidean space））
#inner(x, y) 内积运算（内积的含义要高于点积，点积相当于是内积在欧几里得空间$$的特例，而内积可以推广到赋范向量空间，只要它满足平行四边形法则即可）
#cross(x, y) 叉积运算（向量积，通常记为$\times$，运算结果是一个向量）
#outer(x, y) 外积运算（张量积，通常记为$\bigotimes$，运算结果通常是一个矩阵）
#in1d(x, y) 返回由判断x 的元素是否在y中得到的布尔值构成的数组
#intersect1d(x, y) 计算x和y的交集，返回这些元素构成的有序数组

In [3]:
import numpy as np
array39 = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3]])
array40 = np.array([1,2,3])
array39 + array40

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [4]:
array41 = np.array([[1],[2],[3],[4]])
array39 + array41

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

In [5]:
#左右横向叠加
array42 = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
array43 = np.array([[4, 4, 4], [5, 5, 5], [6, 6, 6]])
np.hstack((array42, array43))

array([[1, 1, 1, 4, 4, 4],
       [2, 2, 2, 5, 5, 5],
       [3, 3, 3, 6, 6, 6]])

In [6]:
#竖直叠加
np.vstack((array42, array43))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5],
       [6, 6, 6]])

In [9]:
print(np.concatenate((array42, array43), axis=0))
print(np.concatenate((array42, array43), axis=1))

[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]]
[[1 1 1 4 4 4]
 [2 2 2 5 5 5]
 [3 3 3 6 6 6]]
